services:
  android:
    build: .
    volumes:
      - .:/app
      - ./artifacts:/artifacts
      - gradle-cache:/opt/gradle-cache
      - android-sdk:/opt/android-sdk
      - npm-cache:/root/.npm
      - ccache:/root/.ccache
    working_dir: /app
    tty: true

volumes:
  gradle-cache:
  android-sdk:
  npm-cache:
  ccache:
